### ISSUE TITLE
String index out of range: 0

### ISSUE THREAD

**Issue by felleg** [alexanderkoller/aaba#7]
I am seeing an error when running the 1.1 release of the aaba program:

```
$ java -jar aaba-1.1.jar ~/Downloads/input.abc -o output.abc
Using default configuration.
Reading melody and chords from: /home/legerf/Downloads/input.abc
Writing arrangement to: output.abc

Exception in thread "main" java.lang.StringIndexOutOfBoundsException: String index out of range: 0
	at java.base/java.lang.StringLatin1.charAt(StringLatin1.java:47)
	at java.base/java.lang.String.charAt(String.java:693)
	at de.saar.coli.arranger.abc.AbcParser.parseAbcNote(AbcParser.java:119)
	at de.saar.coli.arranger.abc.AbcParser.read(AbcParser.java:96)
	at de.saar.coli.arranger.Arrange.main(Arrange.java:59)
```

The content of my `abc` file is the following:
```
X:1
T:Title
%%scale 0.83
%%pagewidth 21.01cm
%%leftmargin 1.00cm
%%rightmargin 1.00cm
L:1/8
M:4/4
I:linebreak $
K:C
V:1 treble nm="Piano" snm="Pno."
V:1
 z6 z"C" C- | CCA,G,"C7" CCA,G, |"G7" D"Gm7b5"^C-C"G7"D- D3 D- | DDA,G, DDA,G, | %4
"C" CA,-A,G,- G,3"C7" C- |$ CCA,G, CCA,G, |"G7" D"Gm7b5"^C-C"G7"D- D3"Em" E |"D7" ^FEDE"G7" =FEDE | %8
"C" C8 | z8 | z8 | z8 | z8 | z8 |$ z8 | z8 | z8 | z8 | z8 | z8 | z8 | z8 | z8 | z8 | z8 | z8 | z8 | %27
 z8 | z8 | z8 | z8 | z8 |] %32
```

The abc file was generated through these steps:
1. Create a score in Musescore 3 (treble clef only, 1 voice only)
2. Export as uncompressed MusicXML file
3. Use https://wim.vree.org/js/xml2abc-js.html to convert the musicxml file to `.abc`

Here is a screenshot of the score in MuseScore 3
![image](https://user-images.githubusercontent.com/7781739/135725010-da1b81da-fa4c-44b9-b5a3-9bc01215a2b4.png)

**Comment by alexanderkoller** [comment]
Hi Félix,

thanks for your interest in aaba, and also for the detailed bug report!

Can you give me a few days to look into this?

My first guess would be that the ABC format is really quite finicky, and it is possible that my ABC parser makes different assumptions than the xml2abc conversion tool. At first glance, I find the chords that are just squished without spaces in between the notes in measure 3 a bit suspicious, but I'll look at it in more detail.

**Comment by felleg** [comment]
Of course! :)

**Comment by felleg** [comment]
Hello! The issue is still present for me, I was wondering if you had time to look into this issue. No pressure :)

**Comment by felleg** [comment]
I see! Thanks for the diagnosis, I will see what I can find.

**Comment by felleg** [comment]
Thanks a ton! I will mark this issue as closed until proved otherwise :)
